### ISSUE TITLE
Create a tutorial

### ISSUE THREAD

**Issue by kadupitiya** [cloudmesh-community/hid-sp18-409#1]
- [x] Find a topic
- [x] Create a tutorial.
- [x] Test it for Linux
- [x] Test it for Windows
- [x] Do the documentation

**Comment by kadupitiya** [comment]
@laszewsk and @tbalson : Can you please check my tutorial and let me know if it is ok.
In the google doc, I see my tutorial topic is approved but I dont see the maximum possible marks.
Thank you.

**Comment by laszewsk** [comment]
there are still bullets in the md which are not needed and would cause issues when translating to other formats

\[ is used wrong, no relative link to the entire program

biggest isssue you use canopy, so we would not use this tutorial at all and not even grade.

no dockerfile provided to also allow deployment in  docker and not just vm

**Comment by kadupitiya** [comment]
@laszewsk :
I can easily remove the canopy. I will remove that.
It doesn't depend on the canopy.  I used it only on windows. 
I will remove all the bullet points.
I did not understand "[  is used wrong" and "no relative link to the entire program".
Why should we provide a docker file for the tutorial?
Creating a docker file for the tutorial was not a requirement when I read the assignment.
I thought we should only do md file.
I added codebase as an additional thing.
What should I do Professor?

**Comment by laszewsk** [comment]
all * need to be removed from code

**Comment by laszewsk** [comment]
uses python 3.5 but python 3.6 is released what is the reason that this needs 3.5 what is the reason this needs canopy and cannot be done with a propper deployment, As we often work in multi python versions environment why can pyenv not be used or leveraged,

**Comment by laszewsk** [comment]
max 5

**Comment by laszewsk** [comment]
you use \[ in code why?

**Comment by kadupitiya** [comment]
No Professor,
It can use python latest version.
I will update that.
There no dependency issue with python 3.5.
It works with python 3.6, I will update that.
I used canopy editor for editing code.

**Comment by laszewsk** [comment]
you do md file, i have script that converts to latex from md.

**Comment by kadupitiya** [comment]
@laszewsk 
Ok. I will remove all * marks.
I will remove canopy and python 3.5.
I still did not see where I used "[ " other than dictionary accessing places.
Do we have to create docker files for this as there was no requirement to add the code base?

**Comment by laszewsk** [comment]
TempDatasetProcessed = TempDataset.where(TempDataset\['t_type'\] == 'TMAX'
	).orderBy('temp', ascending=False).cache()

**Comment by laszewsk** [comment]
i can not past as \ [ will be converted in gitissues

**Comment by kadupitiya** [comment]
@laszewsk 
But we need "[]" for accessing dictionary and list values.
What should I do for that?

**Comment by laszewsk** [comment]
you look wrong please look at your text line by line

**Comment by kadupitiya** [comment]
@laszewsk 
I executed the program in hid-sp18-409/tutorial/temperature_converter.py and it works fine.
Maybe I am not understanding what you are trying to say, professor.
I will join tomorrow online session.

**Comment by laszewsk** [comment]
I will fix it now, next time please look at your md file

**Comment by kadupitiya** [comment]
@laszewsk 
Okay Professor.
 I have been using this online editor for md file editing.
https://stackedit.io/app
I found it on the md file and fixed that. 
That was a copy-pasting issue form the .py file. Sorry Professor, my bad.

**Comment by laszewsk** [comment]
Naturally, when i change in git, you should not change, so I overwrote your changes and made many more changes.  You are free now to change other improvements. In case you need your changes, look at the history

**Comment by kadupitiya** [comment]
Ok. Thank you Professor.

**Comment by kadupitiya** [comment]
@laszewsk 
I have changed all things you have requested and I even created a docker file and makefile for this.
I also added instructions for doker run in the md file.
Is this okay now Professor?
Can you have a look?
https://github.com/cloudmesh-community/hid-sp18-409/tree/master/tutorial
I still dont see the maximum marks possible for this tutorial in the following google doc.
https://docs.google.com/document/d/1L2-wYc7S7hb5u6ZNtKpTvlXqKMkqq-B38hlaBCw-eww/edit#heading=h.zh2i47ik04gx
Thank you.
