### ISSUE TITLE
Technology paper

### ISSUE THREAD

**Issue by kadupitiya** [cloudmesh-community/hid-sp18-409#2]
- [x] Find a topic.
- [x] Do a literature survey.
- [x] Write the paper.

**Comment by laszewsk** [comment]
paper in paper dir compiles perfectly fine on my computer I say

make 
and then I look at report.pdf. all images sow at the end which is intended so you use \ref and \label and you do not forget.

If you have still an issue post output on piazza or attend Monday discussion hours or any of the TAs

**Comment by kadupitiya** [comment]
Okay Professor,
I will participate on Monday discussion.
Thank you.
