### ISSUE TITLE
config.yml

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-409#7]
/swagger/cloudmesh/crime_finder/data
config.yaml is hidden, should be in etc/config.yaml
needs to be moved to ~/.cloudmesh/config-crime.yaml
has smaller datasect in it that depends on properitary gdrive.
needs prg that downloads full data set and tan uploads the data to gdrive if used that way, can use gdrive terminal command, needs configi in seperate dir.
needs to be checked for all configs as basic auth is used and included in makefile, yet it propably shoudl be read and amaged from pythin with for example requests while using a config file ...

**Comment by kadupitiya** [comment]
@laszewsk: 
Do you need me to move the config.yaml outside the crime_finder directory?
Or should I put it in crime_finder directory?
I have added a switch parameter ('switch': 'small') which will actually download the large dataset.
So full dataset download function is there in the python data controller.
For the demonstration, I have used that smaller dataset.
I have never used a gdrive terminal commands.
I will search for that professor.
Thank you.

**Comment by laszewsk** [comment]
I am not yet sure about the answer with the yaml file. I think we want one in the dire in a etc directory within the code. I send a msg to piazza about how to do this and place the yaml file. defenetly when we run it it must not use the one within the code as to avoid that bay accident we put passwords in the file. look at the piazza post

**Comment by kadupitiya** [comment]
Dear Professor,
I did not see that.
I must have missed that.
Will search in Piazza.
Thank you.
